version: '3.7'

services:
  mysql:
    container_name: md_stock
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=md_stock
    ports:
      - "3306:3306"

  adminer:
    image: adminer
    ports:
      - "9090:8080"
    depends_on:
      - mysql